services:
  web:
    build: .
    environment:
      - STRIPE_PUBLISHABLE_KEY=key
      - STRIPE_SECRET_KEY=secret
      - STRIPE_WEBHOOK_SECRET=secret-hook
    volumes:
      - .:/code   # Mount project root
  web_migrate:
    extends:
      service: web
    command: python /code/manage.py migrate
  web_run:
    extends:
      service: web
    command: python /code/manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - web_migrate
    environment:
      PYTHONPATH: "/code"
      DJANGO_SETTINGS_MODULE: "myshop.settings"
  cache:
    image: redis:7.2.4
    restart: always
    volumes:
      - ./data/cache:/data
